### ISSUE TITLE
RuntimeError: No CUDA GPUs are available

### ISSUE THREAD

**Issue by mx5518** [ibanezfd/MAEST#1]
Thanks a lot for your sharing codes. I encountered this issue while running
![69bd7fc49daf21749614a0d3aaa74bb](https://user-images.githubusercontent.com/95353870/229975374-06fb296a-dc59-4d1e-8009-49a71dabc85a.png)
May I ask what is the reason for this? Thank you very much for your reply.

**Comment by ibanezfd** [comment]
It seems like you are working ina machine without GPUs, or Nvidia's CUDA drivers properlly installed. To work from the CPU delete all the ".cuda()" parts in the code, or any other GPU related part.

**Comment by mx5518** [comment]
> It seems like you are working ina machine without GPUs, or Nvidia's CUDA drivers properlly installed. To work from the CPU delete all the ".cuda()" parts in the code, or any other GPU related part.

Thank you for your reply! But my machine has a GPU and the driver installation is also correct because I can run Danfeng Hong's SpectralFormer, so it may not be a problem in this area, but I still cannot run the code at this time. 
![67898a6df28ed1ba977c21700a68187](https://user-images.githubusercontent.com/95353870/230106003-8aa7b182-0190-439e-a167-a9a9a4564f3d.png)

Thank you for your reply again!
best regards！

**Comment by ibanezfd** [comment]
Sorry for the late reply, were you able to solve this issue? Maybe fixing the GPU for the run could help using CUDA_VISIBLE_DEVICES=0 before the python demo.py etc etc.
