### ISSUE TITLE
No such file or directory: '/trained_model_path/checkpoint-XXX.pth'

### ISSUE THREAD

**Issue by DaCraw1** [ibanezfd/MAEST#2]
First of all thanks for sharing the code, I had this issue when running：
FileNotFoundError: [Errno 2] No such file or directory: '/trained_model_path/checkpoint-XXX.pth'

I don't know where to get this file, please have time to answer it.
You wrote 'Please kindly be careful on assigning arguments such as and . Also, remember to change the paths for the arguments and 
 epoches weight_decay output_dir model_path' in the Readme, I don't know how to change it, can you please give an example

**Comment by ibanezfd** [comment]
In the folder "logs" you can find a .pth file with the trained model for each dataset, patch and pixel version. Change the path in the code to the one you want to use.

**Comment by DaCraw1** [comment]
Thank you so much
