### ISSUE TITLE
loading the provided weight file but the accuracy is not the result in the paper

### ISSUE THREAD

**Issue by MC1016** [ibanezfd/MAEST#3]
Hi， Sorry to bother you. When I am testing the Indian dataset, I load the weights file you provided (indian_ft_pt.pth) and use the following command (python demo.py --dataset='Indian' --patches=7 --band_patches=3 --mode='CAF' --flag='test') But the  OA is only 76.25%, and I'm wondering if I'm missing any details?

**Comment by ibanezfd** [comment]
Hi, thanks for noticing. You are right, the checkpoint previously uploaded was an older version. I will upload now the correct version. Sorry for the late replay.
