### ISSUE TITLE
About the classification map.

### ISSUE THREAD

**Issue by teaRRe** [ibanezfd/MAEST#4]
Dr. Ibañez, thank you for the work you do! I have completed the reproduction of the results in your paper. Now there is a question about the visualization of the classification map. I would like to ask you how you made this picture. Is there any relevant source code or method for reference?
![image](https://github.com/ibanezfd/MAEST/assets/33787161/522bbc0b-94c9-4f1e-8063-38a551139811)

**Comment by ibanezfd** [comment]
Thanks for your interest in our work. The visualization maps code was inherited from the code used in SpectralFormer (https://github.com/danfenghong/IEEE_TGRS_SpectralFormer) to match and better compare to their results.
